resources:
- name: deploy-cf-on-aws
  type: git
  source:
    uri: git@github.com:poligraph/deploy-cf-on-aws.git
    branch: develop
    private_key: {{githubsshkey}}
- name: cf-workspace
  type: git
  source:
    uri: git@github.com:Altoros/cf-workspace.git
    branch: master
    private_key: {{githubsshkey}}
jobs:
- name: create-aws-resources
  serial: true
  plan:
  - get: deploy-cf-on-aws
    trigger: true
  - get: cf-workspace
    trigger: false
  - task: create-aws-resources-with-terraform
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: poligraph/ubuntu-ci, tag: "latest"}
      inputs:
        - name: deploy-cf-on-aws
        - name: cf-workspace
      outputs:
        - name: task-temp
      run:
        path: deploy-cf-on-aws/apply-terraform.sh
      params:
        aws_id: {{aws_id}}
        aws_key: {{aws_key}}
        region: {{region}}
        ssl_cert: {{ssl_cert}}
        system_domain: {{system_domain}}
        cf_release: {{cf_release}}
        cf_secret: {{cf_secret}}
        rds_password: {{rds_password}}
        altorosci_pvt_key: {{altorosci_pvt_key}}
  - task: destroy-aws-resources-with-terraform
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: poligraph/ubuntu-ci, tag: "latest"}
      inputs:
        - name: task-temp
        - name: deploy-cf-on-aws
      run:
        path: deploy-cf-on-aws/destroy-terraform.sh
      params:
        aws_id: {{aws_id}}
        aws_key: {{aws_key}}
        region: {{region}}
        ssl_cert: {{ssl_cert}}
        system_domain: {{system_domain}}
        cf_release: {{cf_release}}
        cf_secret: {{cf_secret}}
        rds_password: {{rds_password}}
        altorosci_pvt_key: {{altorosci_pvt_key}}

