resources:
- name: deploy-bosh
  type: git
  source:
    uri: git@github.com:poligraph/deploy-bosh.git
    branch: master
    private_key: {{githubsshkey}}

jobs:
- name: deploy-bosh
  serial: true
  plan:
  - get: deploy-bosh
    trigger: false
  - task: deploy-bosh
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: deploy-bosh/deploy-bosh.sh
      # params:
      #   bosh_manifest: {{bosh_manifest}}
      #   bosh_deployment_network_name: {{bosh_deployment_network_name}}
      #   bosh_deployment_network: {{bosh_deployment_network}}
      #   bosh_deployment_network_subnet: {{bosh_deployment_network_subnet}}
      #   bosh_deployment_network_gw: {{bosh_deployment_network_gw}}
      #   bosh_deployment_network_dns: {{bosh_deployment_network_dns}}
      #   bosh_deployment_network_ip: {{bosh_deployment_network_ip}}
      #   bosh_deployment_user: {{bosh_deployment_user}}
      #   bosh_deployment_passwd: {{bosh_deployment_passwd}}
      #   cli_url: {{cli_url}}
