resources:
- name: deploy-cf-on-aws
  type: git
  source:
    uri: git@github.com:poligraph/deploy-cf-on-aws.git
    branch: master
    private_key: {{githubsshkey}}

jobs:
- name: deploy-bosh
  serial: true
  plan:
  - get: deploy-cf-on-aws
    trigger: false
  - task: download-cli
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: deploy-cf-on-aws/download-cli.sh
